spring:
  application:
    name: webflux-rag
  data:
    mongodb:
      uri: mongodb://localhost:27017/ragdb
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

rag:
  voice:
    openai:
      api-key: ${OPENAI_API_KEY:}
      base-url: https://api.openai.com/v1
      model: gpt-3.5-turbo
    supertone:
      api-key: ${SUPERTONE_API_KEY:}
      base-url: https://supertoneapi.com
      voice-id: ${SUPERTONE_VOICE_ID:91992bbd4758bdcf9c9b01}
      language: ko
      style: neutral
      output-format: wav
